### ISSUE TITLE
V5.0 not work with 11.2.16 - 11.2.20

### ISSUE THREAD

**Issue by pepigo** [Deltafox79/Navicat_Keygen#15]
![image](https://user-images.githubusercontent.com/52339367/60587466-181b3600-9dc7-11e9-9055-15e3846c661b.png)

this problem to many users !

**Comment by Deltafox79** [comment]
Why you no select navicat v11 on Keygen?

**Comment by pepigo** [comment]
sorry I said it wrong, the wrong version is  12.1.16+ (navicat latest version)
This problem has recently arisen with all versions of activation

**Comment by Deltafox79** [comment]
What Language versione you us? English? Because I have Activate 12.1.20 whitout problems.. your problems is exe/dll is already patched whit previus patch.. try on fresh installation.. clean directory and reinstall

![60428651-a0e47700-9bf9-11e9-9636-0b1e8ce277ad](https://user-images.githubusercontent.com/2518850/60649040-83a1e980-9e41-11e9-867e-d681373506ca.jpg)

**Comment by pepigo** [comment]
thanks ,reinstall test success
